### ISSUE TITLE
Need: script that set disable LDAP users as blocked in auth0

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#1]
https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id
Update block to "true"

**Comment by gdestuynder** [comment]
Should also list all email aliases and block any other account that uses that email as their primary identifier (for ex if the email is used by a github account as main identifier)

**Comment by gdestuynder** [comment]
@jdow isn't this implemented?

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #30](https://github.com/mozilla/iam-project-backlog/issues/30) via [**ZenHub**](https://www.zenhub.com/)
