### ISSUE TITLE
Fixup branch protection on repos

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#105]
There are a handful of repos in this GitHub org which
* don't have branch protections enabled
* grant permissions to teams that are intended to be issue editors but not code editors

The `Program-managers (Issue managers)` team had a description indicating that the members of that group could write to issues but not code. I removed the description since that being true depends on all repos to which the team has been granted access having branch protection.

The `Unito Bot` team which contains the unito bot user is granted access to a handful of repos that have no branch protections. This means that a compromise of Unito would allow the attacker to modify code.

Please add branch protection to the following repos

# Repos that `Program-managers (Issue managers)` have rights to edit code

* cis_functions
* dino-park-front-end
* dino-park-search
* dino-park-tree
* dino-park-dev-tools

# Repos that `Unito Bot` has rights to edit code

* gsuite-community-drive-driver
* iam-infra
* iam-profile-faker
* dino-park-front-end
* dino-park-search
* dino-park-tree
* dino-park-dev-tools

Here's the code I used to find these. We may want to run this is a nightly auditor (maybe in lambda) : https://gist.github.com/gene1wood/203dfa28ee1f2daa3757af17d6a5299f

**Comment by gdestuynder** [comment]
I wonder if it would make sense to run this as enforcement code instead, ie that forces-fix on all repo daily @gene1wood

**Comment by gene1wood** [comment]
I've updated the branch protection settings in all these repos to constrain who can write to branches like `master`, `production` and `development`

Some repos which already had branch protection (but not preventing Unito Bot, Auth0 Bot and Program Managers from writing to the codebase) don't have the "Include administrators Enforce all configured restrictions for administrators. " setting checked so for example @fiji-flo can write to master in mozilla-iam/dino-park-front-end without review, though others require review. If this is intentional leave it, if not check that box.
