### ISSUE TITLE
Check RPs use the delegation endpoint/user sessions rechecks

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#11]
In order to check that RPs are correctly handling user sessions (ie follows: https://wiki.mozilla.org/Security/Guidelines/OpenID_Connect#Session_handling )

we could check that the delegation endpoint is queried at the minimum. If not, its an indicator that the sessions are not being re-checked.

**Comment by gdestuynder** [comment]
This is what the call looks like in the logs:

`{
  "date": "2016-12-12T22:53:27.509Z",
  "type": "sd",
  "connection": null,
  "connection_id": "",
  "client_id": "poy4bMcyUJ7v2RuOTjs8WVDVcfCHbqqY",
  "client_name": "social-ldap-pwless.testrp.security.allizom.org",
  "ip": "35.161.34.157",
  "user_agent": "lua-resty-http/0.08 (Lua) ngx_lua/10006",
  "user_id": "ad|Mozilla-LDAP-Dev|gdestuynder",
  "user_name": ""
}`

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #33](https://github.com/mozilla/iam-project-backlog/issues/33) via [**ZenHub**](https://www.zenhub.com/)
