### ISSUE TITLE
Random locale used for "you must be logged in" error page

### ISSUE THREAD

**Issue by hwine** [mozilla-iam/mozilla-iam#115]
What I expect:
- all pages should be displayed to me using the locale specified in my browser ("en_US" for me)

What happened:
- I get "login" pages in "random" locales displayed to me. (see screen shot)

STR:
1. be logged into a mozillian's acount
1. edit your profile
1. right click the context menu on the "Add Identity" button, and open in another container (or private window) via the "Open Link in a new Container Tab".
1. See the banner message in English reading "You must be logged in to continue. ", which is expected
1. note that URL and text uses a different locale (see screen shot) **<= *NOT* expected.**
1. close the tab
1. repeat steps 3-5 & note that a _different_ locale is used. **<= *NOT* expected.**

![Mozillians_sk_login](https://user-images.githubusercontent.com/132412/84096288-6a40e000-a9b6-11ea-8199-fa7a71970dd9.jpg)

**Comment by hwine** [comment]
Sigh - after repro at least 5 times, (Brazilian Portuguese, French, an Asian dialect, and at least one other), after I submitted the report, it started behaving again.

**Comment by djmitche** [comment]
I have seen this as well.  I reported it, but I can't remember where -- maybe discourse?
