### ISSUE TITLE
Process and store email delivery records

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#12]
Currently AWS SES notifications regarding email delivery are sent to an AWS SNS Topic which is in turn subscribed to by a Google Group.

Searching in Google Groups for a specific user's delivery attempt isn't possible because the message content is JSON and Google Groups is expecting plan text.

I'd recommend we write a AWS Lambda function to take these SNS notifications, parse the JSON and insert each record into a DB (e.g. AWS Dynamo) so that we can search them.

**Comment by gene1wood** [comment]
Or emit the events to MozDef instead of storing them in a DB.

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #34](https://github.com/mozilla/iam-project-backlog/issues/34) via [**ZenHub**](https://www.zenhub.com/)
