### ISSUE TITLE
Link user identities automatically by email

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#13]
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/15_

Example: https://github.com/auth0/rules/blob/master/rules/link-users-by-email.md

**Comment by gdestuynder** [comment]
https://github.com/mozilla-iam/auth0-deploy/pull/86
https://github.com/mozilla-iam/auth0-deploy/issues/15

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #35](https://github.com/mozilla/iam-project-backlog/issues/35) via [**ZenHub**](https://www.zenhub.com/)
