### ISSUE TITLE
 Modify email template to provide magic link and number code

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#14]
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/22_

Also, change email send confirmation page to something that would accept the code and continue the auth flow.

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #36](https://github.com/mozilla/iam-project-backlog/issues/36) via [**ZenHub**](https://www.zenhub.com/)
