### ISSUE TITLE
Cannot access to my account

### ISSUE THREAD

**Issue by 0uros** [mozilla-iam/mozilla-iam#143]
Hello there, I'm not sure if this is the place where I can do a suggestion about accounts, but I don't see a better place at the moment.

On August 13 I registered in the forum, to be able to make a suggestion, it turns out that I made a change of mail in the forum, because it was linked to an old email from my Mozilla account.

The point is that later it occurs to me to make that same change, but in the Mozilla account itself, and I did. Now it turns out that if I want to log in, it does the procedure for creating a new account, and my username is listed as taken ([@Ouros](https://connect.mozilla.org/t5/user/viewprofilepage/user-id/9497)). It is indistinct if I start with my Firefox account, or the two emails involved (the previous one and the one I changed it for)

Right now I don't have access to my Firefox account, I don't know if I should communicate on the other hand (since it is not specified) or if I should give up that account (which would screw me to lose an account in two days, hahaha)

I hope that this error is read and that I can communicate with someone who can help me, thank you in advance.

**Comment by bkochendorfer** [comment]
:wave: This repository is for Mozilla's internal IAM system and people.mozilla.org, not Firefox Accounts or Connect. That's okay though! Let's see if we can get you redirected to the correct place.

 If you can access your account, or a new account on https://connect.mozilla.org, you can message [Jon](https://connect.mozilla.org/t5/user/viewprofilepage/user-id/6) and they can assist you with your connect account.

If you have questions about Firefox accounts I would reach out on https://support.mozilla.org/en-US/

Hope this helps, thanks!
