### ISSUE TITLE
Add additional text to the Passwordless e-mail template to help it avoid Gmail spam filter

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#15]
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/49_

Gmail marks Auth0 Passwordless e-mails as Spam. The reason given is:

It's similar to messages that were detected by our spam filters.

According to this site (emphasis added):
Your content has problems. It’s been judged not valuable or contains content that is such a hard sell that it triggers Google’s content-based filters. Things like all-image emails or overuse of sales promotional words and phrases are to blame here, so make sure there’s legitimate editorial content in your messages to balance out the sales pitches. Bottom line: send more valuable email, email that people actually want, and they’ll stop flagging it as spam. Make sure you have prominent unsubscribe links and use the List-Unsubscribe header option if your email service provider offers it so that people who don’t want to be on your list can leave instead of flagging you as spam.

Recommend adding more text to avoid Spam filter. Auth0 might also have some suggestions.

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #37](https://github.com/mozilla/iam-project-backlog/issues/37) via [**ZenHub**](https://www.zenhub.com/)
