### ISSUE TITLE
 Potentially use the same rule for all LDAP access control

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#16]
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/79_

Current we use one rule per LDAP application + LDAP group match for access control.
This means that we potentially end up with many rules (depending on how many RPs actually want this, and want a special, different group that we hardcode on their behalf).

I don't expect this to come up often, but if it does, we should probably rewrite the rule logic to accommodate in a single rule for clarity and speed.

Ex:

rules = { 'vpn_mozdef': ['client name 1', 'client name 2', ...], 'moco': ['client name 1', ...], ...}

**Comment by tristanweir** [comment]
@jdow @gdestuynder Did we resolve how we were going to do this in the future? Copying it over but I think we have an answer on this

**Comment by gdestuynder** [comment]
I think the original rule was written this way - that said, ideally, it should load a json file that has the rules.
The logic itself is fairly straightforward (arguably, as well as the code)

**Comment by gdestuynder** [comment]
See also https://github.com/mozilla-iam/sso-dashboard/ - the list might be used by the dashboard in order to only show the apps the user has access to, thus might need to be consumable by both parties.

**Comment by andrewkrug** [comment]
Meeting regarding this today.  I think we might need to add an architecture component.

**Comment by gdestuynder** [comment]
Brainstorm results: https://docs.google.com/document/d/1v2ceqo4rUIkhFzW4QszXSkOmjhGpjkgNy9-9jCN1bwA/edit#heading=h.88k9ttsb9ziu

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #38](https://github.com/mozilla/iam-project-backlog/issues/38) via [**ZenHub**](https://www.zenhub.com/)

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #39](https://github.com/mozilla/iam-project-backlog/issues/39) via [**ZenHub**](https://www.zenhub.com/)
