### ISSUE TITLE
Revert auth0-deploy/pull/85 workaround now that Auth0 has deployed fix

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#18]
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/93_
_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/95_

https://github.com/mozilla-iam/auth0-deploy/pull/85 works around an issue where a Duo user can be permanently locked out after multiple failed attempts. (see https://github.com/mozilla-iam/auth0-deploy/issues/82)

Now that Auth0 has deployed [this fix](https://github.com/mozilla-iam/auth0-deploy/issues/82#issuecomment-276587949) we should revert our workaround in https://github.com/mozilla-iam/auth0-deploy/pull/85 and test Auth0's more complete solution.

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #41](https://github.com/mozilla/iam-project-backlog/issues/41) via [**ZenHub**](https://www.zenhub.com/)
