### ISSUE TITLE
Update CloudTrail configuration in partinfra

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#21]
Currently the partinfra AWS account is using the v1 configuration of the secure cloudtrail storage system

https://mana.mozilla.org/wiki/display/SECURITY/AWS+Secure+CloudTrail+Storage+System

Please do the following :

In us-east-1 only, please delete the "DeployCloudTrailCloudFormationStacks" cloudformation stack which will disable CloudTrail in all regions

Next, deploy the new global CloudTrail config by deploying this CloudFormation template in any single region (only deploy once total, for example deploy it once in only us-east-1)

https://s3.amazonaws.com/infosec-cloudformation-templates/configure_cloudtrail_to_use_mozilla_secure_storage_globally.json

Let the stack deploy and confirm that it completes and shows the CloudFormation stack as green, complete.

**Comment by flamingspaz** [comment]
*clicks undo button*

**Comment by hmitsch** [comment]
Sorry for the foo. I take all the blame. Sorry, sorry, sorry!

**Comment by flamingspaz** [comment]
Filed https://github.com/mozilla/partinfra-terraform/pull/88

**Comment by flamingspaz** [comment]
:x: old stack
:pencil2: new stack
