### ISSUE TITLE
Delete community-ops-cloudtrail s3 bucket containing old CloudTrail logs

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#22]
You probably want to delete the community-ops-cloudtrail s3 bucket in the partinfra AWS account as it contains 1+ year old cloudtrail logs

**Comment by flamingspaz** [comment]
Gene, do you want the whole bucket gone or just everything older than 1y?

**Comment by gene1wood** [comment]
My assumption was that this bucket is not currently used for logging cloudtrail logs and all of the logs present in the account are old. If I'm mistaken and it's currently being used for logging cloudtrail then we should hold on deletion and talk bout this more.

Do you see current logs or do you just mean that the newest logs are only say 11 months old not 12 months old?

**Comment by flamingspaz** [comment]
oops you were right, none of the logs are less than 12 months old and I can't see anything that would log to it, so it's gone.
