### ISSUE TITLE
Refactor S3 bucket access methods

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#23]
Currently the S3 buckets in the partinfra account use a combination of S3 ACLs, S3 Bucket Policies and IAM Policies to govern access to their contents. The combination of these 3 methods of access control likely result in unexpected permissions. For example, despite the clear intent that the "jenkins-ses-iam" IAM user only have rights to "ses:SendRawEmail" because of the IAM policy applied to that user, "jenkins-ses-iam" actually has rights to delete terraform configurations in the partinfra-tfsync S3 bucket because of an S3 ACL in place on that bucket. This means that users and roles in your account likely have unexpected permissions related to S3.

"[As a general rule, AWS recommends using S3 bucket policies or IAM policies for access control. S3 ACLs is a legacy access control mechanism that predates IAM](https://aws.amazon.com/blogs/security/iam-policies-and-bucket-policies-and-acls-oh-my-controlling-access-to-s3-resources/)"

I'd recommend going through your S3 buckets and determining the intent of the access control settings in each one and change them to be rendered in IAM policies or S3 bucket policies but not S3 ACLs

**Comment by gene1wood** [comment]
The new bucket blog.mozillaindia.org is also configured with this account wide ACL and should be changed to use IAM user and S3 bucket policies.

```
{
    "grants": {
        "communityit-aws": [
            "FULL_CONTROL"
        ]
    },
    "lifecycle_rules": [
    ],
    "versioning": {
    }
}
```

**Comment by flamingspaz** [comment]
- [ ] badges.mozilla.org
- [ ] blog.mozillaindia.org
- [ ] discourse-paas-production-content
- [ ] discourse-paas-staging-content
- [ ] discourse-staging-emailin
- [ ] elasticbeanstalk-us-east-1-484535289196
- [ ] elasticbeanstalk-us-west-2-484535289196
- [ ] equal-rating-wp-content
- [ ] feedthefox-dev
- [ ] feedthefox-prod
- [ ] guides.mozilla-community.org
- [ ] innoprize-hostmaster-email
- [ ] jenkins-duplicity-backup
- [ ] jenkins-public-duplicity-backup
- [ ] lock-prototype
- [ ] mainwp-paas-remote-backups
- [ ] marathon-production-duplicity-backup
- [ ] marathon-staging-duplicity-backup
- [ ] mesos-elb-logs
- [ ] mozillians-admin-dev
- [ ] mozillians-dev.allizom.org-admin
- [ ] mozillians-s3-logs
- [ ] mozillians.allizom.org-admin
- [ ] mozillians.org-admin
- [ ] partinfra-ansible-bucket
- [ ] partinfra-cloudtrail
- [ ] partinfra-docker-registry
- [ ] partinfra-private-docker-registry
- [ ] partinfra-tfsync

**Comment by gene1wood** [comment]
You know what, I'm mistaken. I'd called out the bucket ACL of

```
{
    "grants": {
        "communityit-aws": [
            "FULL_CONTROL"
        ]
    },
    "lifecycle_rules": [
    ],
    "versioning": {
    }
}
```

as being a problem but it is not. This ACL is the default ACL which grants the root account user full rights to the bucket. It's this ACL which enabled the root account user to delegate control to AWS IAM. Ideally this would be the ACL for all the buckets.

Other ACLs than this type though are probably best fixed up.

For example there are buckets like `partinfra-ansible-bucket`, `partinfra-tfsync`, `mozillians-admin-dev` which do not grant `READ_ACP` to the root user thus preventing IAM users and roles (like our security auditing role) from reading the access control settings for the bucket. 

Or the `feedthefox-dev` bucket which grants via ACL READ, WRITE and READ_ACP to all amazon users (in all accounts), effectively the bucket is publicly writable

Or `equal-rating-wp-content`, `badges.mozilla.org`, `lock-prototype` which is publicly readable. This may be intentional. You should check that the content in the bucket is classified as public data. Another good practice would be to add a README.md to the bucket clarifying that it's only to be used for public data.

There are also some buckets that explicitly call out READ WRITE READ_ACP and WRITE_ACP being granted to the root account user which is another way of saying FULL_CONTROL. These ACLs are fine they just look different.

Here's more info on the ACLs http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html

**Comment by flamingspaz** [comment]
I've started manually adding bucket policies to our non-terraform managed buckets, and a PR for others:
https://github.com/mozilla/partinfra-terraform/pull/105

**Comment by flamingspaz** [comment]
I've reviewed all the buckets and left some at default and some have had their permissions tightened.

Some of our buckets store pretty sensitive information so they have been restricted to just the roles that need to interact with them (+ InfoSecAudit role, let me know if there are buckets you still can't access).

Buckets that are intended to be public now have a README.txt stating as such.

I've left the Mozillians buckets as they are - We'll most likely create new buckets with new permissions during the migration.
