### ISSUE TITLE
AWS "partinfra" account IAM user tanner has administrive AWS access

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#24]
It looks like the partinfra user `tanner` was meant to have some level of access below administrative by looking at the policies applied. If this is the case, there is unfortunately a few errors in the policy that grant the account administrative access

* By granting `iam:AttachUserPolicy` this enables the user to attach an administrative policy to itself
* By granting the combination of `iam:PassRole` and `ec2:*` the user can create an ec2 instance with ssh access that the user controls, attach an administrative role to the instance, login to the instance, acquire temporary STS credentials with that administrative role and either act as an administrator from there or attach and administrative policy to the user

**Comment by gdestuynder** [comment]
Clarification: this is the partsys AWS account

**Comment by flamingspaz** [comment]
Admin access was intentional since the original role was too restrictive, I'll review the old role to make sure it's functional and secure, then revoke admin access.

**Comment by flamingspaz** [comment]
Filed new ops role/permissions at https://github.com/mozilla/partinfra-terraform/pull/93

**Comment by flamingspaz** [comment]
Tanner now has the permissions defined at https://github.com/mozilla/partinfra-terraform/blob/master/iam.tf#L38
