### ISSUE TITLE
Please file issues for inclusion in the IAM Project Board at mozilla/iam-project-backlog

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-iam#25]
We cannot bring issues from this repo into our IAM Project Board. If you want to ensure your issue is worked, please file it here: https://github.com/mozilla/iam-project-backlog/issues and alert @hmitsch or @tristanweir

IAM Project Board is here: https://github.com/orgs/mozilla/projects/3

**Comment by gdestuynder** [comment]
we no long have this board closing
