### ISSUE TITLE
github / oauth issue

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#29]
@klint

Hi @klint,

Is there a way to reach you? I have questions about your GitHub login to some Mozilla properties and would need your help, if you see this.

Thanks!

**Comment by klint** [comment]
Sorry I'm sorry but I just realized I forgot to answer.

**Comment by gdestuynder** [comment]
oh hey @klint !
is there any easy way to reach out to you on a non-public channel? (email, slack, irc, etc.)

**Comment by klint** [comment]
Hi
You can reach me at: klint at free.fr
Cheers

2017-09-28 19:53 GMT+02:00 Guillaume Destuynder (:kang) <
notifications@github.com>:

**Comment by gorhill** [comment]
I am no longer able to login to Mozilla Discourse using my GitHub account, I have been trying to login at different times today and I always end up receiving an error:

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? 

I did approve authorization. This all used to work fine not long ago.

**Comment by hmitsch** [comment]
@LeoMcA FYI

**Comment by gdestuynder** [comment]
I've moved this issue to https://github.com/mozilla-iam/mozilla-iam/issues/32 as so not to spam @klint  too much.
Please open new issues when unrelated :)
