### ISSUE TITLE
Using Bugzilla 2FA for Mozillians login

### ISSUE THREAD

**Issue by aneeshusa** [mozilla-iam/mozilla-iam#30]
Hi, I'm a volunteer on the Servo project and I recently received an email saying I would need to connect my GitHub.com account for future logins to my Mozillians.org profile and continued NDA resource access. Looking at [the faq](https://wiki.mozilla.org/IAM/Frequently_asked_questions), it seems like GitHub was chosen to satisfy a 2FA requirement. I would prefer not to use GitHub to login, and I already have 2FA set up on my Bugzilla account. Would it be possible to also support Bugzilla as an alternate identity provider?

**Comment by hmitsch** [comment]
Hi @aneeshusa, 

thanks for finding your way into this project repo. You rock!

We are checking in with Bugzilla people from time to time to evaluate if we would want to use Bugzilla as IDP (Identity Provider). So far there is no clear answer. 

I suggest to close this issue until we actually decide between the IAM Team and the Bugzilla team that this is a shared goal. Hope this works for you.

Best regards,
   Henrik
