### ISSUE TITLE
issue with discourse/github login

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#32]
From @gorhill (moved from https://github.com/mozilla-iam/mozilla-iam/issues/29#issuecomment-332443516)

> I am no longer able to login to Mozilla Discourse using my GitHub account, I have been trying to login at different times today and I always end up receiving an error:
> 
>     Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?
> 
> I did approve authorization. This all used to work fine not long ago.
> 
> Note that I tried to log in using a brand new profile on FF57. The UR: where the error message occur is:
> 
> https://discourse.mozilla.org/auth/failure?message=access_denied&origin=https%3A%2F%2Fdiscourse.mozilla.org%2Flatest&strategy=auth0
> 
> Note that in the "Authorized OAuth Apps" entry in my GitHub account says:
> 
>     Mozilla Identity and Access Management
>     https://sso.mozilla.com
> 
> However when I load above URL in a new tab, it is redirected to:
> 
> https://auth.mozilla.auth0.com/login?client=[...]
>

**Comment by gdestuynder** [comment]
@gorhill it looks like your GitHub account has 2FA disabled. I'm not sure why you're not getting the correct error message though (Leo might know).

I suspect that enabling 2FA will give you correct access to discourse. 

See also https://wiki.mozilla.org/IAM/Frequently_asked_questions#Q:_How_can_I_set_up_two-factor_authentication_.282FA.29_for_my_github_account.3F for help setting up 2FA

**Comment by gorhill** [comment]
> I suspect that enabling 2FA will give you correct access to discourse.

That is a problem, I don't want 2FA on my GitHub account. I barely use a mobile phone, and I may let expire whatever phone number I have on it at any time, so 2FA through phone is really not an option for me. Anyway, this is my problem, maybe I will try more to log in with the other options (Google account, email messages), but they also failed at the time, though I didn't try to investigate whether the issue was on my side as much with these other options.

**Comment by gdestuynder** [comment]
@gorhill as per the FAQ any access that is privileged requires 2FA (which means an LDAP or GitHub account because we can verify 2FA has been used there). For access such as posting in Discourse public discussions and any other such application, the non-2FA accounts will work fine.

Note that, in case you would still want to use 2FA, a phone number is not necessarily required. You can also use a U2F token (Yubikey for example), or an OTP generator application (free, such as FreeOTP on Android).
I would generally recommend to use an app such as FreeOTP as it's also safer than SMS, and of course, does not depend on your phone or phone number. (We have a bit on info on these things here as well, if interested https://infosec.mozilla.org/fundamentals/rationales.html#mfa )
