### ISSUE TITLE
IAM for mozilla-standards

### ISSUE THREAD

**Issue by annevk** [mozilla-iam/mozilla-iam#33]
At the moment @dbaron and I maintain https://github.com/mozilla-standards. It's an organization for handling intellectual property rights (IPR) concerns for Mozilla employees that participate in developing standards. What we need is the ability for all Mozilla employees to be able to join that organization if they want (without going through us) and ensuring that employees that leave Mozilla are removed from the organization.

I heard something like this might be available Q2 2018; filing this mainly to track the request.

**Comment by hwine** [comment]
My understanding from initial discussions with @dbaron is that non-employees will also need access at times (contractors was the example given). I.e. there will be exceptions that need to be managed.

**Comment by hmitsch** [comment]
Confirming the following scope item on our IAM Roadmap:

**Objective:** Allow GitHub private repository access to users in a certain IAM group
**Key Results:**
- User with GitHub login can access a private github.org/mozilla repository
- Admins of github.org/mozilla are managed by an IAM group
- github.org/my-org can leverage IAM to set which users should have write access to it

Currently there is no confirmed delivery date but Q2/2018 is still a time range that might work.

-Henrik

/cc @gdestuynder @jeffbryner

**Comment by gdestuynder** [comment]
we had some discussions around access control for GitHub with @hwine and @gene1wood as well.
Given that GitHub (non-enterprise) has no OIDC or similar functionality, our current, early plans/discussions are around associating GitHub identities with Mozilla IAM and having a robot that ensure access rights are correct for repositories that want to use this functionality

**Comment by hwine** [comment]
Correct - **AND** we also need to make the decisions on (at least) the 'mozilla' org including folks who are neither staff nor "NDA'd Mozillians".
