### ISSUE TITLE
Retrieve user's GitHub ID via API

### ISSUE THREAD

**Issue by hwine** [mozilla-iam/mozilla-iam#34]
To implement various audit and organization automation, the IAM API needs to be able to return a user's GitHub account ID (preferred) or login (usable). We'll want to query by GitHub Account ID to find the associated ldap email address. We'd also like to get the GitHub account IDs (plural) associated with an ldap account. (One ldap user can have several GitHub accounts.)

GitHub identifies accounts in two primary ways:
 - ID's which never change [1] - usable in all API queries
 - login (human readable strings - like 'hwine') which can be changed - usable in Web UI, and exchangeable for the ID

The email address associated with the GitHub account can be changed at any time, and there are no API calls to convert an email address into a valid account identifier.

[1] IDs are either [integers in v3 API](https://developer.github.com/v3/users/), or [strings in v4 API](https://developer.github.com/v4/scalar/id/). The v4 format can be converted into a v3 format, so storing & returning the v4 format is preferred.

**Comment by gdestuynder** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1434428

**Comment by hmitsch** [comment]
@hwine how urgent is this need? Is this something you need us to address in the next 2 weeks or can/should we schedule this scope for later?

Best regards,
   Henrik

**Comment by hwine** [comment]
@hmitsch -- sounds like you're running sprints ;) -- over 2 weeks is fine. Ideally, it would be usable before the end of Q1 -- at least as far as me being able to test it.

Our (Firefox Security Operations) goal is be using this mapping (github ID -> ldap email address) to notify ldap users of conditions GitHub which need their attention. I can role that part out quickly for certain teams in the Firefox group which are entirely staff or NDA'd mozillians. Usage & adoption on a wider scope (with contributors that may not even have a mozillians account at this time) will be a longer process.

I updated the [initial statement](#issue-292947602) to reflect we actually need the lookup in both directions, as that wasn't obvious.

Did I leave anything else out of the "spec"?

**Comment by gdestuynder** [comment]
Proposed implementation

## Modify user profile schema:
See the new field `user_id` in the `email` struct.

```
{
	"user_id": "ad|Mozilla-LDAP-Dev|lmcardle",
	"timezone": "Europe/London",
	"active": true,
	"lastModified": "2017-03-09T21:28:51.851Z",
	"created": "2017-03-09T21:28:51.851Z",
	"userName": "lmcardle@mozilla.com",
	"displayName": "Leo McArdle",
	"firstName": "Leo",
	"lastName": "McArdle",
	"preferredLanguage": "en_US",
	"primaryEmail": "lmcardle@mozilla.com",
	"emails": [
		{
			"value": "lmcardle@mozilla.com",
			"verified": true,
			"primary": true,
			"name": "work",
                        "user_id": "dn=mozilla.com,cn=lmcardle"
		},
		{
			"value": "leomcardle@gmail.com",
			"verified": true,
  			"primary": false,
			"name": "github",
                        "user_id": "9348586"
		}
	],
	"phoneNumbers": [
	],
	"uris": [
	],
	"nicknames": [
	],
	"SSHFingerprints": [
	],
	"PGPFingerprints": [
	],
	"picture": "https://s.gravatar.com/avatar/ec6e85d15f8411d32f97f5d8a4eab2d3?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Flm.png",
	"shirtSize": "M",
	"groups": [
		"mozilliansorg_bar",
		"mozilliansorg_foo"
	],
	"authoritativeGroups": [
			{
				"created": "2010-01-23T04:56:22Z",
				"lastUsed": "2010-01-23T04:56:22Z",
				"name": "moco",
				"uuid": "reserved_mozilla_1"
			},
			{
				"created": "2010-01-23T04:56:22Z",
				"lastUsed": "2010-01-23T04:56:22Z",
				"name": "mofo",
				"uuid": "reserved_mozilla_2"
			},
			{
				"created": "2010-01-23T04:56:22Z",
				"lastUsed": "2010-01-23T04:56:22Z",
				"name": "nda",
				"uuid": "reserved_mozilla_3"
			},
			{
				"created": "2010-01-23T04:56:22Z",
				"lastUsed": "2010-01-23T04:56:22Z",
				"name": "mozdef1.private.scl3.gmail",
				"uuid": "5a5munnfxYjqkaN0su1Kl7USxbqkILQN"
			}
		]
}

```

## Write auth0 to CIS publisher
Copy HRIS publisher and write auth0 publisher from it.

The publisher should:
- scan for github userids per profile and integrate
- that's it ;-)

The publisher will get more functionality in the future for other things

**Comment by hwine** [comment]
@gdestuynder Is it impractical to use the v4 GitHub id? That feels more "future proof" as v4 adds a namespace (user vs org), while v3 just has an integer. (I can provide the algorithm to convert.)

To be concrete, the 'mozilla-services' organization has:
```json
# v4
    "user": {
      "id": "MDQ6VXNlcjEzMjQxMg==",
      "login": "hwine"
    }

#v3
{
  "login":"hwine",
  "id":132412
}
```

**Comment by gdestuynder** [comment]
we don't currently get the v4 id from the OIDC endpoint

**Comment by gdestuynder** [comment]
@hwine just double-checking, would having the GitHub ID be enough (i.e. not the login, if you wanted it, you'd fetch it from GitHub) ?

**Comment by hwine** [comment]
@gdestuynder Two points:
1. Yes, id is better than login.
2. v3 id (integer) is going to be harder to obtain over time -- it will be replaced by a "global relay id" (base64 string). So, safest to store as string, not int. (See [this reply](https://platform.github.community/t/query-organization-using-id-and-permanence-of-id-value/5320/2?u=hwine) for more information.)
a) It might be possible to obtain the global relay id today through the use of special [preview headers](https://developer.github.com/v3/#graphql-global-relay-ids) in your current request.

**Comment by gdestuynder** [comment]
The id is currently planned to be stored as a string. Right now, we do not control how the request is made during the oauth login, thus can't grab additional data with preview headers. However, this can be a feat request to auth0.

Additionally, I suspect we *could* create a custom oauth2 identity provider authenticator that makes the right query instead of using auth0's built-in. That said, I think we'd want to first store the v3 id (just to ensure we don't have too many changes at once).

I'm a little worried though if:

- we store v3 id
- time passes
- we replace v3 id by v4, will this break things for you and others, or will github translate them in all APIs transparently?
- if we add a new attribute, it's kind of odd and very github-specific

**Comment by hwine** [comment]
+1 on not making it GitHub specific.

While I haven't been able to get anyone from GitHub to state on the record, I would expect the v3<->v4 id mapping would remain the same trivial function it is today. That is, we could provide that mapping for our internal uses. (Conversion requires support for base64 encoding & decoding, and basic string operations.) I do not expect GitHub to translate the id formats at all.

For the uses I foresee making of this data, I feel quite comfortable being able to access data no matter which one is stored (and I don't need to know which one is stored - it's self evident).

Are there any other identified use cases for accessing the GitHub id? 

One caveat: I've been looking at this just from the 'user' and 'org' id viewpoint. The answer may be different for other GitHub entities (e.g. 'teams'). I've been assuming any group mapping would be storing the ids it needs elsewhere. If that isn't a valid assumption, please let me know and I'll spot check a few other such identifiers.

**Comment by gdestuynder** [comment]
currently i think this is the only use case, though im sure more will come up eventually as we use github so heavily

**Comment by gdestuynder** [comment]
See https://github.com/mozilla-iam/cis/pull/108
