### ISSUE TITLE
Set new name for dev auth0 LDAP connector

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#4]
Currently the LDAP connector in auth0 auth-dev is `auth0ldap-dev1`. Please change this (by setting up a new connector) to the name `Mozilla LDAP Dev`

Please change the prod LDAP connector from `MozillaLDAP` to `Mozilla LDAP` as well.

This should bring these names into conformance with the other connections.

This likely requires re-setting up the connectors (sorry)

**Comment by jdow** [comment]
Spaces are not allowed in the connector name:

Payload validation error: 'String does not match pattern ^[a-zA-Z0-9][-a-zA-Z0-9]*$: Mozilla LDAP Dev' on property name (The name of the connection. Must start with an alphanumeric characters and can only contain alphanumeric characters and '-'. Max length 35).

**Comment by jdow** [comment]
I renamed dev to "Mozilla-LDAP-Dev" and prod to "Mozilla-LDAP".
