### ISSUE TITLE
Support for W3C Web Authentication API (webauthn) (Yubikey etc.)

### ISSUE THREAD

**Issue by jwatt** [mozilla-iam/mozilla-iam#41]
We'll be shipping Web Authentication support in Firefox soon, targeting Firefox 60:

https://lists.mozilla.org/pipermail/dev-platform/2017-December/020813.html
https://bugzilla.mozilla.org/show_bug.cgi?id=webauthn

Web Authentication is a big step forward in terms of blocking phishing attacks, and it allows us to drop the dependency on users having a smartphone [to hand] in order to log in to Mozilla properties.

**Comment by gdestuynder** [comment]
hi
we would love to support this.

Right now, the plan is to have it supported by DuoSecurity for "LDAP" accounts and by Firefox Accounts (which is to-be integrated as well). We expect Google and GitHub will support it as well.

**Comment by gdestuynder** [comment]
Update:
- Duo Beta is completed and I believe this is implementable, though this only works as 2FA for LDAP accounts and requires changing the enrollment frontend on login.mozilla.com
- Auth0: public response => https://auth0.com/blog/web-authentication-webauthn-overview-demo-tool/  (WebAuthn.me) this is not yet fully integrated in Auth0 SSO solution though
