### ISSUE TITLE
Fire Drag add on...problems w/- FB messenger

### ISSUE THREAD

**Issue by Condobloke** [mozilla-iam/mozilla-iam#42]
1. Am I in the right place ??
2. If so.....the add on....fire drag, by Eric Tsang....has issues with facebook messenger. 
It has comments to this effect in its reviews.
No update has happened since release over 6 months ago.
Is Eric still alive?
Can I expect any action/improvement to this add on?
If the answer to question 1 is No....please direct me !

Brian

**Comment by hmitsch** [comment]
Hi @Condobloke, 

I am afraid this is not the best place for your question. May I suggest heading to:
https://discourse.mozilla.org/c/add-ons/add-on-support

Best regards,
   Henrik
