### ISSUE TITLE
Solve session length issues possibly causing users to have to re-provide their LDAP password

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#46]
Currently our [`SSO Session Absolute Timeout`](https://auth0.com/docs/appliance/dashboard/settings#session) is set in Auth0 prod to the default of 3 days.

It's possible this is causing users to have to re-provide their LDAP password after weekends.

* Gather the Google Analytics data to determine if indeed there is a spike of password logins as compared to autologins on Mondays
* Update the `SSO Session Absolute Timeout` in Auth0-dev to 4 days
* Test to make sure there are no adverse effects
* Deploy this change in prod by opening a support request with Auth0 asking them to make the change in our RTA
* Gather data over a week or two and compare to see if it changed the rate of users being prompted for their ldap password.

Once this is completed we can begin to look at #47

**Comment by gene1wood** [comment]
@gdestuynder reports "request for changing SSO Active to 4d on prod sent" indicating that he's sent a request into Auth0 for them to change the "SSO Session Absolute Timeout" value from 3 days to 4 days in the production Auth0 RTA instance

**Comment by gene1wood** [comment]
@gdestuynder and I will look at Dev on April 2nd and continue with prod if things look good.

**Comment by gdestuynder** [comment]
which is done in prod rta
