### ISSUE TITLE
Define a sane session flow management for RPs w/ auth0 when using OIDC

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#5]
Currently, we're thinking about:
* using the id_token with a 30d expiry (configurable)
* requesting and default-configuring RPs to use the id_token expiry as application/client session expiry (when id_token expires, user is logged out of the application/client)
* requesting and default-configuring RPs to introspect and reload groups information (ACLs/Scopes) based on that every 15min (or prior to processing whichever next user-agent query after a 15min mark)

**Comment by peterbe** [comment]
Interesting that I have come to the same conclusion more or less. 

You can renew the id_token and you should probably **always** do that (e.g. renew it every time you check that it's still valid). 

The refresh_token should apparently not be used for repeatedly asking auth0 if it's still valid. So if you have the refresh_token, you'd need to use the delegation API to convert it to an id_token anyway.

**Comment by gdestuynder** [comment]
yes, as long as you renew the user can in fact stay logged in.
in fact i guess we could have a shorter expiration (say 7 days) on the id_token. it means as long as you use it within 7 days, you session is up forever. If you stop using it or the renew fails, the session will always end after 7 days (this is the fail-safe).

On top of that the introspection ensure that as connectivity works properly, if your user is disabled or access changes, either you access can be changed real time or the rp will log you out "instantly"* (no need to wait for end of session).

*where instantly is  0-15min

**Comment by peterbe** [comment]
This topic is not about how long you get to be signed in. It's about how long you're allowed to be entirely inactive.

**Comment by gdestuynder** [comment]
The session handling is in place for AirMo and the test site, and is defined at:
https://wiki.mozilla.org/Security/Guidelines/OpenID_Connect

It is exactly as per this issue discussion, thx!
