### ISSUE TITLE
Update github-security-settings

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#55]
After discussing with @gene1wood @andrewkrug @jdow we think that we should discuss this with the whole IAM team as well:

- Should we use tags instead of `master` vs `production` branches? This is more standard and a little easier for onboarding new people

- Should we use CODEOWNERS with github enforcement for branch protection? This allow removing some review requirements for bening changes within the same repos.

- We *should* actually add the risk score for each repo for changes (standard level impact of the project in case of compromise or operational issue, etc.)

**Comment by gdestuynder** [comment]
@akatsoulas @johngian @hidde

**Comment by gdestuynder** [comment]
Note: I believe we should just use tags - specially than the master vs production requirements were related to auth0's CI which we no longer need

**Comment by hidde** [comment]
I’d love us to use tags as they are more explicit in what they label, especially when combined with a CHANGELOG. 

Also +1 for CODEOWNERS.
