### ISSUE TITLE
Map current state of IAM UX

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/mozilla-iam#59]
Goal: create an updated map of the IAM ecosystem from the perspective of the user. 

Parameters:
- This is the *current* state of IAM
- To be posted in a space where commenting & feedback is achievable (realtime board)
- Sets the stage for alignment on proposed iterations of primary user touchpoints
   - NLX, Dashboard, Profile/Org Chart utility

**Comment by m-branson** [comment]
Making analog progress:

![iam-ux-analog-v1](https://user-images.githubusercontent.com/18686986/42115372-6ea7e79a-7ba7-11e8-9361-3a983e6a76e0.jpg)

[On team drive here](https://drive.google.com/open?id=1uvPGn4g-y-FC7L3kN5y7w9XRq8tkQeCM)

Will digitize & create more direct connection points next week for interactive feedback.

@hmitsch @gdestuynder re: Google, is it considered a 1FA IdP?

**Comment by gdestuynder** [comment]
very neat cards :)

Google is currently considered a 1FA IdP even if 2FA is enabled, since we don't know

**Comment by m-branson** [comment]
The current mapped state of IAM UX is now [further developed & here](https://realtimeboard.com/app/board/o9J_kzEB-Ls=/) for review/commenting (I recommend zooming in to about 140-180% for best size).

Feel free to drop comments with questions, edits, etc. I will review them when back from holiday with the intent to improve this & then move on to mapping our ideal UX based on our latest technical alignments.

@gdestuynder: Thanks for the early feedback, I believe I have incorporated everything other than the auth0 rule engine/auth endpoint. As this is from the perspective of our users, I've left out anything that is not front-end facing (hence the need for technical architecture documentation as well).

cc @hidde @hmitsch @jeffbryner @gene1wood @andrewkrug @akatsoulas @johngian

**Comment by m-branson** [comment]
Comments are still welcome, closing as I will incorporate feedback from @gdestuynder and move onto ideal UX architecture proposal #68.
