### ISSUE TITLE
How to differentiate issues that are closed and resolved compared to closed because we don't have time right now?

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#63]
I've got two questions that we should decide

1. How should we as a team be deciding that certain bugs or feature requests are not a priority and as such should be closed and not done? What time period should we all be using to make this call (e.g. If a bug won't be fixed in the next 1 month, then it should be closed and not fixed, or if a feature won't be developed in the next 3 months it should be closed and not developed ever)
2. For bugs and feature requests which are decided to be closed not because they are resolved but because they aren't currently a priority, how can we differentiate these issues so that later we have the potential for pulling them the backlog?

The issue that brought this question to mind for me was mozilla-iam/auth0-custom-lock#71 where a user requested a feature and a use case and we closed it.

I'd hope we could have a consistent method for assessing if feature requests should be closed. And if they are closed because they aren't a priority currently, we should have some way to go back to them later.

**Comment by gene1wood** [comment]
@hmitsch This feels like a process question that you'd probably have insight on

**Comment by gene1wood** [comment]
Ah looks like there's a parallel thread on this in discourse

https://discourse.mozilla.org/t/process-improvement-proposal-close-backlog-issues-with-wontfix/29731

**Comment by hidde** [comment]
I’d propose we have the discussion in the above Discourse thread ^
