### ISSUE TITLE
Map ideal UX architecture proposal

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/mozilla-iam#68]
Map ideal future UX architecture proposal for IAM based on discussion from #58 and current UX architecture map (#59). 

Initial architecture proposal should include the following touchpoints:

- [x] NLX
- [x] SSO Dashboard
- [x] Mozilla RP Anonymous Access
- [x] Central Identity Utility (proposed)
- [x] Central Profile Utility (new Mozillians.org w/Profile v2)

**Comment by m-branson** [comment]
Proposed UX Map is [here](https://realtimeboard.com/app/board/o9J_kzEB-Ls=/) and ready for initial review with @hmitsch & @flekkowich this sprint. Will call for further team feedback shortly.

![iam map proposed](https://user-images.githubusercontent.com/18686986/42913725-533ee2e8-8aab-11e8-81a3-ae509c759081.png)

**Comment by m-branson** [comment]
**For all tagged on this comment:** please review the `IAM Map: Proposed` [here](https://realtimeboard.com/app/board/o9J_kzEB-Ls=/), including comments that are present from me. 

This is following today's review with @hmitsch and @flekkowich where we theorize that perhaps the `Central Identity Utility` already exists as the Auth0 Admin. I pose the question there: is it possible to create a front-end for it that our users may engage with to manage their identities (and set their preferred identity)?

I will also be adding this as a topic for the next tech alignment which I will miss due to holiday. It would be great if this conversation could progress from the technical perspective regardless.

For reference: the question above in as posed on the map:
![screen shot 2018-07-19 at 2 24 48 pm](https://user-images.githubusercontent.com/18686986/42971152-22fe60e4-8b60-11e8-869f-9ad1c772cf65.png)

@gdestuynder @jeffbryner @andrewkrug @gene1wood @hidde @akatsoulas @johngian @fiji-flo @flekkowich @hmitsch

**Comment by gdestuynder** [comment]
I understand the "Central Identity Utility" as the place where you set what you login as ("I login with FxA" "I login with GitHub" etc.)

Currently this does not exist, what you login as is hard-coded. In the future I think we have 2 paths forward:

1 - the Central Identity Utility where you would indeed select that. If so, this does not exist in Auth0 management console, and this not something we can easily add to NLX as the user needs to be authenticated. 

2 - "KR 14 [EIS, Parsys][LARGE] Plan the refactor the login ratcheting (“login v2”) to accommodate large audience sites" leads to using some kind of account *linking* (not verification) where the user does not need to set or understand their identity

**Comment by hmitsch** [comment]
+1 on Option 2 ... and the notion of _pandora's box_ 😄

**Comment by m-branson** [comment]
Thanks for the response @gdestuynder. This specifically is a flag for me:

>...where the user does not need to set or understand their identity

Would not most users care to have visibility of, and control over, what identity they log in with across various RPs? << This is precisely why the current proposal is a central identity utility, to provide this level of access, control and understanding of their identity providers to our users.

I read KR 14 as saying that users will be able to log in with any identity at any RP and they will all be linked to their profile. I would agree to this, though at the RP level users should still be able to identify what identity provider they are logged in with & have access to changing it. Eg; User A currently uses Google but now prefers to use GitHub for login.

Perhaps I'm misunderstanding and this is what KR 14 intends? If so, it would be good to more accurately reflect this.

**Comment by m-branson** [comment]
Thanks @gdestuynder, that makes complete sense. Diagrams are helpful! I've just added a mtg for Aug 1 (@gene1wood is optional and very welcome!) to discuss this topic as you proposed yesterday in slack:

>...we'll still have to answer it at some point (the solution 2 from the comment that is). probably a demo/slides with gene & I to you/jeff/megan for ex, and if it makes sense at this point, tech align all together (everyone in IAM that wants to participate that is)

Hopefully this gives enough time to you & Gene to prepare diagrams. Agreed this will be helpful for us all to align together.
