### ISSUE TITLE
Ensure LDAP groups get reflected on auth0 side periodically (without requiring an LDAP login)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#7]
Currently the auth0 LDAP agent does not reflect groups "live". it only update them when a login with LDAP occurs (as in a complete login flow where the ldap password is entered).
This means pooling the id_token attributes or user profile won't reflect current LDAP group until logout/login.

We want these to be close to live instead.

**Comment by gdestuynder** [comment]
Here's a possible solution (tested) - lets call it **solution A**:

On LDAP group change, send an API call to auth0 for user:update_user such as:

`curl -H "Authorization: Bearer ..." -X PATCH  -H "Content-Type: application/json" -d '{"user_metadata":{"group":["group_a", "group_b"]}}' https://auth-dev.mozilla.auth0.com/api/v2/users/ad%7CMozilla-LDAP-Dev%7Cgdestuynder`

Where the `group` is in user.user_metadata (the Auth0 API forbids writing directly to `user.*` data structure).

Then, a rule catches all logins and delegation requests (thus group update requests) to rewrite the groups membership entirely:

```
function (user, context, callback) {
  user.user_metadata = user.user_metadata || {};
  //Note: not checks being made here as we do want this to be undefined or empty array if
  //user.user_metadata.group is undefined or empty.
  user.groups = user.user_metadata.group;
  callback(null, user, context);
}
```

There's still an issue with this though, while the rule trigger during the delegation endpoint call, somehow auth0 does not update the user structure internally.

**Comment by gdestuynder** [comment]
Note: with auth0 when calling the delegation endpoint it is very important to request the profile and/or openid scope otherwise auth0 returns the openid scope WITHOUT updating it (this might be a bug, i'm not sure - technically it's correct but it's also illogical)

that means any RP using the delegation endpoint (most of mozilla RPs) MUST specify a scope when calling the delegation endpoint

TODO: kang to document this

**Comment by gdestuynder** [comment]
See also https://github.com/mozilla-iam/auth0-deploy/pull/86 (closed)

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #31](https://github.com/mozilla/iam-project-backlog/issues/31) via [**ZenHub**](https://www.zenhub.com/)
