### ISSUE TITLE
Document SSO form

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#8]
https://mana.mozilla.org/wiki/display/SECURITY/SSO+Request+Form

**Comment by gdestuynder** [comment]
Done
@jdow r+- plz :)

(its all at https://mana.mozilla.org/wiki/display/SECURITY/SSO+Request+Form)

**Comment by jdow** [comment]
r+

**Comment by gdestuynder** [comment]
got the other r on the mana doc
