### ISSUE TITLE
Recovery codes returned are all [object Object]

### ISSUE THREAD

**Issue by k88hudson** [mozilla-iam/mozilla-iam#82]
I was setting up a new 2fa device today and I wasn't able to see any recovery codes:

![image](https://user-images.githubusercontent.com/1455535/45323302-b5e00480-b518-11e8-8d68-581dc09fe822.png)

**Comment by hmitsch** [comment]
@andrewkrug @gdestuynder @gene1wood do you know where that screenshot comes from and what the problem might be?

-Henrik

**Comment by gene1wood** [comment]
@k88hudson What was the URL or service you were at when you saw this? Was this from Duo? Maybe Firefox Accounts?

**Comment by gdestuynder** [comment]
this is login.mozilla.com

**Comment by k88hudson** [comment]
Yes, this is login.mozilla.org; also, hlangi filed a bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1490133

As of this morning, it seems I'm able to generate codes again.

**Comment by gene1wood** [comment]
@k88hudson Cool, glad it ended up working. Ya that bugzilla ticket is the best place to track it as I don't think the codebase for login.mozilla.com is in github.com/mozilla-iam
