### ISSUE TITLE
Write automation to deprovision users from Mozilla Wireless

### ISSUE THREAD

**Issue by fox2mike** [mozilla-iam/mozilla-iam#83]
Talked with @gdestuynder about this, and here's the issue, so we can track it. 

1. We would like to roll out wireless specific passwords for all users of the "Mozilla" SSID across Mozilla spaces. This uses the localDB option within Clearpass. 
2. As part of this, we would like to automatically deprovision users that are no longer valid. 
3. The clearpass endpoint you want to hit is $CLEARPASS_URL/local-user/user-id/{user_id} with the user_id (smani@mozilla.com for example) with a DELETE call

Would be awesome to have this by September 28th. Thanks! /cc @rtucker-mozilla

**Comment by gdestuynder** [comment]
project @ https://github.com/mozilla-iam/clearpass-driver

**Comment by fox2mike** [comment]
@gdestuynder I'm thinking we follow the litmus test outlined in [Wireless Auth with OTP](https://docs.google.com/document/d/1cScirnFGDYZQlKzgXvz0v0O-k7m41iktwAV9BOSpdjQ/edit#heading=h.jehtnwbh6s22) doc, specifically the comment around allowed groups with access? 

I envision something like 

1. You check if the user is part of the specific LDAP group, if YES, check if they have something on Clearpass's LocalDB
2. NO - No Action, YES - call the DELETE on their userid

**Comment by gdestuynder** [comment]
@fox2mike sounds good to me, do note though that the group selection is somewhat important, for ex `hris_is_staff` means only staff gets wifi access (like today) and NDA'd contributors do not.
Also, this should match whatever clearpass client uses for the account creation (what does it use?)

on the flip side its easy to change in the future, its just a setting.

**Comment by gdestuynder** [comment]
Done at https://github.com/mozilla-iam/auth0-scripts/pull/34
