### ISSUE TITLE
Passwordless Login email qualified as spam

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/mozilla-iam#87]
This was reported by @ashwin-phadke.

_Mozilla IAM_ login emails are ending up in Bulk and Junk folders.

Email headers say:
```
Spam state 11\MCE
Score 17
Spam cause is a huge string may be encoded so it appears gibberish
```

Is there anything we can do about this? This is important, as our move to _low-friction authentication_ will result in more people using _passwordless email_ authentication (e.g. Common Voice, SUMO Respond).

**Comment by gene1wood** [comment]
@ashwin-phadke

Can you share the full headers and the name of the email provider that is marking the email as spam?

**Comment by ashwin-phadke** [comment]
Here it is
[I have removed some personally identifiable information.]

 : `

Return-Path: <@us-west-2.amazonses.com>
--

Received: (qmail 20455 invoked from network); 27 Oct 2018 12:55:15 -0000
Received: from unknown (10.50.250.70)
by 0 with QMQP; 27 Oct 2018 12:55:15 -0000
X-REDF-SPAM:T=L;
X-DKIM-Verification: dkim domain=sso.mozilla.com; verify=0; BodyHash=0; TestMode=-1; SAligned=1; RAligned=1;
dkim domain=amazonses.com; verify=0; BodyHash=0; TestMode=-1; SAligned=0; RAligned=0;
X-SPF-Verification: spf domain=us-west-2.amazonses.com; result=pass; clientip=54.240.27.31; SAligned=0; RAligned=0;
X-DMARC-Verification: dmarc=no_record; dkim=-; spf=-; pct=0; domain=null;
Received: (qmail 12123 invoked from network); 27 Oct 2018 12:55:14 -0000
X-IN-VDRT-SpamState: 11\MCE
X-IN-VDRT-SpamScore: 17
X-IN-VDRT-SpamCause:  gggruggvucftvghtrhhoucdtuddrgedtkedrheeggdeitdcutefuodetggdotefrodftvfcurfhrohhfihhlvgemucftgfffkffhhfenuceurghilhhouhhtmecufedttdenucdnofetkffnkffpifculddujedmnecujfgurheptgfhvffukffoffggsegrtderreertdejnecuhfhrohhmpefoohiiihhllhgrucfuuffquceonhhorhgvphhlhiesshhsohdrmhhoiihilhhlrgdrtghomheqnecuffhomhgrihhnpegruhhthhdtrdgtohhmpdhmohiiihhllhgrrdhorhhgnecukfhppeehgedrvdegtddrvdejrdefudenucevlhhushhtvghrufhiiigvpedt
X-Remote-IP: 54.240.27.31
X-REDIFF-SENDER-VERIFY: D=-2, DKIM=0, P=G
Received: from a27-31.smtp-out.us-west-2.amazonses.com (54.240.27.31)
by 0 with ESMTPS (AES128-SHA256 encrypted); 27 Oct 2018 12:55:13 -0000
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=qmlvmdv2lsceiusbcnxadqs5l3jwtumh; d=sso.mozilla.com;
t=1540644910;
h=Content-Type:From:To:Subject:Message-Id:Date:MIME-Version;
bh=FtfoGU+9pRfRgCssLW62UfO4Q4Y/EpU+N8rRe16ARZA=;
b=d0nHERNIEA9kKHscNBPR3h/oIublOkDTlTC4leJEHS6s71qQIJZsvZNiuc1B+Csn
5KnCPvJbSdvQTcQBqptBe391/GVEdJSnG+wv5cCpiv9lnZblMYU5fBVZjvNvikFEyBI
uFL4mfUBWgk32VZ7fGLVAv4og4TR1Ir+n51TOyzo=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=7v7vs6w47njt4pimodk5mmttbegzsi6n; d=amazonses.com; t=1540644910;
h=Content-Type:From:To:Subject:Message-Id:Date:MIME-Version:Feedback-ID;
bh=FtfoGU+9pRfRgCssLW62UfO4Q4Y/EpU+N8rRe16ARZA=;
b=InUWMtDShw3zZUynK0ZCIzXyokME0TNqk6SbAKUcK7WS70YWuHprVFELvHIp+Ppn
C3AGCm2Ow/6wJNoIPD0usXLQHGWCUVTFFDL5RaqwIQgC87TcWUi98lsRLlo9Yu13rsl
jiYBr4nA4HGr5PMDo840z2xI9rPGa9Tlo2dS1Fy0=
Content-Type: multipart/alternative;
boundary="----sinikael-?=_1-15406449098670.6265140196774155"
From: Mozilla SSO <noreply@sso.mozilla.com>

Subject: Welcome to discourse.mozilla.org
Message-ID: <01010166b597b3c9-86bfcef5-f4b1-40c8-aace-cf67fc9740a8-000000@us-west-2.amazonses.com>
X-Mailer: nodemailer (2.3.0; +http://nodemailer.com/; SES/1.3.0)
Date: Sat, 27 Oct 2018 12:55:10 +0000
MIME-Version: 1.0
X-SES-Outgoing: 2018.10.27-54.240.27.31
Feedback-ID: 1.us-west-2.uHogrXyy+XKMRmZyxDC5UOCBhNiEyoF5M/tmxXz7Wmc=:AmazonSES

`

**Comment by gene1wood** [comment]
@ashwin-phadke Thank you for the headers.

When you were redacting personally identifiable data did you remove any headers? If so is it possible to share those headers and indicate what's been redacted? What email provider are you using?

I've googled for the "X-IN-VDRT-SpamCause" and other "IN-VDRT" headers to try to determine what software or service it is but have been unable to find anything, I'm hoping that if I can determine what email provider you're using I can figure out what antispam thing they're using.

The headers look correct though, SPF passes, it's DKIM signed. I'm unsure of the DKIM validation as I don't see a "Authentication-Results" header.

Anyhow, once I know what was redacted I should be able to figure this out.

**Comment by ashwin-phadke** [comment]
Sure, the headers have almost the right amount of validity for the email to pass through the spam filter but somehow the email provider has flagged it I suppose and it is not the first time this has happened, I also have marked it safe once or twice earlier , all seemed fine between the periods but then these mails again start ending up in either the Bulk folder or the Junk folder.
Email Provider : Rediffmail 
Here I can put the entire header just as required : 

```


Return-Path: <01010166b597b3c9-86bfcef5-f4b1-40c8-aace-cf67fc9740a8-000000@us-west-2.amazonses.com>
--
Delivered-To: ashwinphadke12@rediffmail.com
Received: (qmail 20455 invoked from network); 27 Oct 2018 12:55:15 -0000
Received: from unknown (10.50.250.70)
by 0 with QMQP; 27 Oct 2018 12:55:15 -0000
X-REDF-SPAM:T=L;
X-DKIM-Verification: dkim domain=sso.mozilla.com; verify=0; BodyHash=0; TestMode=-1; SAligned=1; RAligned=1;
dkim domain=amazonses.com; verify=0; BodyHash=0; TestMode=-1; SAligned=0; RAligned=0;
X-SPF-Verification: spf domain=us-west-2.amazonses.com; result=pass; clientip=54.240.27.31; SAligned=0; RAligned=0;
X-DMARC-Verification: dmarc=no_record; dkim=-; spf=-; pct=0; domain=null;
Received: (qmail 12123 invoked from network); 27 Oct 2018 12:55:14 -0000
X-IN-VDRT-SpamState: 11\MCE
X-IN-VDRT-SpamScore: 17
X-IN-VDRT-SpamCause:  gggruggvucftvghtrhhoucdtuddrgedtkedrheeggdeitdcutefuodetggdotefrodftvfcurfhrohhfihhlvgemucftgfffkffhhfenuceurghilhhouhhtmecufedttdenucdnofetkffnkffpifculddujedmnecujfgurheptgfhvffukffoffggsegrtderreertdejnecuhfhrohhmpefoohiiihhllhgrucfuuffquceonhhorhgvphhlhiesshhsohdrmhhoiihilhhlrgdrtghomheqnecuffhomhgrihhnpegruhhthhdtrdgtohhmpdhmohiiihhllhgrrdhorhhgnecukfhppeehgedrvdegtddrvdejrdefudenucevlhhushhtvghrufhiiigvpedt
X-Remote-IP: 54.240.27.31
X-REDIFF-SENDER-VERIFY: D=-2, DKIM=0, P=G
Received: from a27-31.smtp-out.us-west-2.amazonses.com (54.240.27.31)
by 0 with ESMTPS (AES128-SHA256 encrypted); 27 Oct 2018 12:55:13 -0000
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=qmlvmdv2lsceiusbcnxadqs5l3jwtumh; d=sso.mozilla.com;
t=1540644910;
h=Content-Type:From:To:Subject:Message-Id:Date:MIME-Version;
bh=FtfoGU+9pRfRgCssLW62UfO4Q4Y/EpU+N8rRe16ARZA=;
b=d0nHERNIEA9kKHscNBPR3h/oIublOkDTlTC4leJEHS6s71qQIJZsvZNiuc1B+Csn
5KnCPvJbSdvQTcQBqptBe391/GVEdJSnG+wv5cCpiv9lnZblMYU5fBVZjvNvikFEyBI
uFL4mfUBWgk32VZ7fGLVAv4og4TR1Ir+n51TOyzo=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
s=7v7vs6w47njt4pimodk5mmttbegzsi6n; d=amazonses.com; t=1540644910;
h=Content-Type:From:To:Subject:Message-Id:Date:MIME-Version:Feedback-ID;
bh=FtfoGU+9pRfRgCssLW62UfO4Q4Y/EpU+N8rRe16ARZA=;
b=InUWMtDShw3zZUynK0ZCIzXyokME0TNqk6SbAKUcK7WS70YWuHprVFELvHIp+Ppn
C3AGCm2Ow/6wJNoIPD0usXLQHGWCUVTFFDL5RaqwIQgC87TcWUi98lsRLlo9Yu13rsl
jiYBr4nA4HGr5PMDo840z2xI9rPGa9Tlo2dS1Fy0=
Content-Type: multipart/alternative;
boundary="----sinikael-?=_1-15406449098670.6265140196774155"
From: Mozilla SSO <noreply@sso.mozilla.com>
To: ashwinphadke12@rediffmail.com
Subject: Welcome to discourse.mozilla.org
Message-ID: <01010166b597b3c9-86bfcef5-f4b1-40c8-aace-cf67fc9740a8-000000@us-west-2.amazonses.com>
X-Mailer: nodemailer (2.3.0; +http://nodemailer.com/; SES/1.3.0)
Date: Sat, 27 Oct 2018 12:55:10 +0000
MIME-Version: 1.0
X-SES-Outgoing: 2018.10.27-54.240.27.31
Feedback-ID: 1.us-west-2.uHogrXyy+XKMRmZyxDC5UOCBhNiEyoF5M/tmxXz7Wmc=:AmazonSES

```

Hope this helps.

**Comment by gene1wood** [comment]
@ashwin-phadke  thank you for the additional details. I've been unable to find anything on the internet that speaks to the spam and dkim header details so I've emailed customer support at your email provider to get more information on what software they're using and what these header values mean. I'll update here if/when I hear back.

**Comment by hmitsch** [comment]
From a chat:
> all emails are now appearing in inbox as of a previous week.

... closing issue.

**Comment by gene1wood** [comment]
I tried communicating with your email provider and we went back and forth a few times but wasn't able to communicate what I was trying to learn from them. Glad it started working.

**Comment by ashwin-phadke** [comment]
![login](https://user-images.githubusercontent.com/23502062/56081958-c0f16f00-5e30-11e9-8622-bd0d19d157a0.jpg)

The issue has yet again emerged, I wonder why it keeps happening consistently though, if they are qualifying legit email as spam as every email from that domain is almost ending up in spam/junk, only Mozilla newsletter appears in Primary.

**Comment by gene1wood** [comment]
Can you contact your email provider and ask them how to whitelist an email sender?
