### ISSUE TITLE
Is it not possible to login to discourse.mozilla.org without "MFA, "2FA"?

### ISSUE THREAD

**Issue by erosman** [mozilla-iam/mozilla-iam#88]
I understand that this is probably not the correct place for this post, but I have no idea where to post it.

Due to recent changes, I have not been able to login to discourse.mozilla.org
It no longer accept anything but "MFA, "2FA" Firefox Account which seem rather surprising for a public help/support forum.

I am a reviewer on AMO and I am able to login to AMO, reviewers AMO, bugzilla etc without 2FA.

Installing additional applications/software just to be able to login to a forum seems excessive for this particular purpose.

I have also been getting regular emails from discourse.mozilla.org about missed topics that I can no longer participate in. I had to move the support for all my extensions to GitHub as a result.

**Comment by hmitsch** [comment]
Hi @erosman,

thank you for reaching out. We agree with your position and plan to roll out a change to our IAM system before the end of the year which will allow a "non 2FA" login to Discourse using Firefox Accounts.

Best regards,
   Henrik

/cc @LeoMcA @gdestuynder

**Comment by erosman** [comment]
Hi @hmitsch 

It is still not possible for me login to discourse.mozilla.org

I have been getting PMs and support request that I can not respond to (I still get the email notification).
The Firefox account that I can login to as an AMO addon reviewer, is not accepted by discourse.mozilla.org due to 2FA, neither are Github or Email.

Once again, I understand when banks use 2FA for security in login and account access, but a public forum is not a bank.

**Comment by hmitsch** [comment]
Hi @erosman,

thanks for reaching out again. I opened a ticket to get your account downgraded from FxA to passwordless email.

We agree that access to a public forum should not require 2FA. That's why we are working on _deratcheting_ (see https://github.com/mozilla-iam/mozilla-iam/blob/master/docs/deratcheting-user-flows.md).

Hope to be back with better news in the next 20 hours.

Best regards,
   Henrik

**Comment by erosman** [comment]
Hi @hmitsch 
Happy New Year 

It is a new year and I am still unable to login to discourse.

Can someone at least do me a favour and reply to my support topics, saying the user can no longer login and ask them to please use the new support site:
https://github.com/erosman/support/issues

I got another support question today that I cant reply to.

https://discourse.mozilla.org/t/support-copy-plaintext/
https://discourse.mozilla.org/t/support-edit/
https://discourse.mozilla.org/t/support-foxyimage/
https://discourse.mozilla.org/t/support-foxylink/
https://discourse.mozilla.org/t/support-foxypac/
https://discourse.mozilla.org/t/support-foxytab/
https://discourse.mozilla.org/t/support-historia/
https://discourse.mozilla.org/t/support-igoogle/
https://discourse.mozilla.org/t/support-imdb-plus/
https://discourse.mozilla.org/t/support-refresh-blocker/
https://discourse.mozilla.org/t/support-replace/
https://discourse.mozilla.org/t/support-text-multicopy/
https://discourse.mozilla.org/t/support-url-multicopy/

Thank you

**Comment by hmitsch** [comment]
Hi @erosman,

I am really sorry for the inconveniences. Manually changing your login methods was rejected (that was the '20 hours' comment). 
In the last few working days leading up to the seasonal break, we hit some unexpected issues with further delayed a permanent fix of the issue impacting you ("_Deratcheting_"). We continue on this thread of work in early January.

I posted your requested message in 3 of the mentioned Discourse threads. These were the threads that held messages which are rather recent (last 6 months) and unanswered.

Best regards,
   Henrik

**Comment by 2alin** [comment]
Same problem here, I initially set up github as my authentication method (months ago) and now I can't log in because it's asking me to have "MFA", "2FA". I would love to change the auth method to email account instead and a password, but I can't do that either.

**Comment by hmitsch** [comment]
Hi @2alin,

Thanks a lot for checking in. The deployment of our _Deratcheting_ release will also solve your issue. We will post about it during the month of January on the [IAM](https://discourse.mozilla.org/c/iam) and [ParticipationSystems](https://discourse.mozilla.org/c/participationsystems) Discourse categories.

Please accept my apologies for the mess we put you through.

Best regards,
   Henrik


Best regards,
   Henrik

**Comment by decembre** [comment]
"Installing additional applications/software just to be able to login to a forum seems excessive for this particular purpose."
Yes.
So when it should be possible to login simply to the forum ?

**Comment by erosman** [comment]
@hmitsch May I bother you again to answer to this query?
https://discourse.mozilla.org/t/translating-options-pages/19604/21

Can you please ask him to contact via Github?
https://github.com/erosman/HTML-Internationalization/issues

**Comment by 2alin** [comment]
@hmitsch 
Hi, I'm still unable to login to discourse. If I try to login using github credentials, I get this:

![screenshot_20190215_131613](https://user-images.githubusercontent.com/4089035/52879539-06413b00-3125-11e9-96ad-5eab5a682b35.png)

and if I try to login using my email (same as github), I receive an access email but then I get this error:

![screenshot_20190215_131700](https://user-images.githubusercontent.com/4089035/52879316-6edbe800-3124-11e9-9e56-d42075b486be.png)

who do I need to talk with or what do I need to do to either assign a password to my account or change my default login option (github)? It's really frustrating that I haven't participated in your forums for months.

**Comment by craigbaker** [comment]
I've also been unable to use the forums for quite some time due to this. Any solution would be much appreciated.

**Comment by gdestuynder** [comment]
Hi,
this should be fixed now (see https://discourse.mozilla.org/t/mozilla-iam-sso-improving-login-experience-through-authentication-flexibility/36274)
