### ISSUE TITLE
Change auth0 auth-dev github extension to pull from development branch

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#9]
Currently it pulls from master. Change it to development. It might require disabling and re-enabling the extension as there's no apparent way to change the branch.

**Comment by gdestuynder** [comment]
Currently we cannot change settings or delete the extension
Depends on https://support.auth0.com/tickets/16844

**Comment by gdestuynder** [comment]
note, we can now change settings.
I would actually vote to keep master and wontfix this though, since we've been using it for a while and it's rather standard.

**Comment by hmitsch** [comment]
Issue moved to [mozilla/iam-project-backlog #32](https://github.com/mozilla/iam-project-backlog/issues/32) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gene1wood** [comment]
[closed](https://github.com/mozilla-iam/iam-project-backlog/issues/32#issuecomment-288453611)
