### ISSUE TITLE
Unicode character in nickname profile field prevents user login to SAML RPs

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-iam#98]
@lonnen discovered this bug.

# Steps to Reproduce

1. Go to phonebook and set your LDAP user's `nickname` to contain an emoji, for example `John 🤔 Doe`
   * Lonnen set his nickname to `Lonnen "🤔" Lonnen` which triggered the problem
   * This likely applies to a whole class of characters, not just this [unicode character](https://www.fileformat.info/info/unicode/char/1f914/index.htm)
   * The `"` characters are not the cause as we tested with just those and login worked
2. Attempt to login to an OIDC RP, you should have success
   * Known sites that do work with emoji are phonebook, sso.mozilla.com, gmail, and casa
3. Attempt to login to a SAML RP
   * The two we tested that manifested the problem were Egencia and ServiceNow

# Expected Results

Successfully logging in

# Actual Results

On log-in I am sent through a series of redirects to a page saying `Could not validate SAMLResponse`, and then to a page that never renders but quickly displays the follow (retrieved from network logs)

```
<strong>invalid_request</strong>: 
You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn&#39;t find your session. 
Try logging in again from the application and if the problem persists please contact the administrator
```

and ultimately I am directed to an `external_logout` page.

**Comment by gene1wood** [comment]
When this bug is solved please let Lonnen know so he can put his emoji back in his `nickname`

**Comment by lonnen** [comment]
ty!

**Comment by cshields** [comment]
I'm not sure it is worth the time to fix this in phonebook if phonebook is going to replaced <soon?>..

**Comment by gene1wood** [comment]
Nah this isn't a phonebook issue, this is a problem with either Auth0, our Auth0 rules or our SAML configurations for our SAML RPs. Phonebook is just the tool used to set this field in the profile. When we move away from phonebook to something else, that too would ostensibly be able to set unicode characters in this field.

**Comment by rtucker-mozilla** [comment]
One concern here is how GADS will handle syncing of unicode. We've seen issues where GADS will fail syncing unicode.
