### ISSUE TITLE
No Mozillians groups in Auth0 (but they do exist in Person API)

### ISSUE THREAD

**Issue by LeoMcA** [mozilla-iam/mozilla-iam#99]
I've [got a user](https://discourse.mozilla.org/t/no-access-to-nda-forums-even-though-account-is-in-the-nda-access-group-according-to-mozillians/36949) whose Mozillians groups are returned when I query Person API v1, but aren't when querying Auth0 (which only returns their LDAP groups instead).

The user_id is `ad|Mozilla-LDAP|martin`.

**Comment by gdestuynder** [comment]
may be related to https://github.com/mozilla-iam/cis_functions/pull/45/commits/81bf2905d555796f389ee86ec1606e7935eba33c

**Comment by gdestuynder** [comment]
nope this piece of code works as expected

**Comment by gdestuynder** [comment]
after some testing if i just trigger a group change everything works fine (ie things work as expected right now)

**Comment by gdestuynder** [comment]
please re-open if this occurs again, i cannot find anything wrong or reproduce at the moment
the user has the right groups in auth0 as well
